name: notes
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: any
  intl: any

  drift: ^2.26.1
  drift_flutter: ^0.2.4

  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0

  infinite_scroll_pagination: ^5.0.0

  freezed_annotation: ^3.0.0
  theme_tailor_annotation: ^3.0.2
  
  dart_date: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  theme_tailor: ^3.0.2
  freezed: ^3.0.6

flutter:
  uses-material-design: true
